baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FMS Choir'
theme = 'mainroad'

[Params]
    description = "Forestwood Middle School Choir"
    copyright = "Forestwood Middle School Choir Booster Club"
    dateformat = "2006-01-02"
    customCSS = ["css/custom.css"]
    # spiritLink = "https://kristees.biz/collections/swim-and-dive"
    # spiritLinkText = "Kristees FMHS Swim & Dive"
    # uil = "UIL Conference 6A, Region 2, District 5"
    mainSections = ["posts"]
    googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap"
    # HeaderImage = "2024-district-champsx800.webp"

[Params.style.vars]
    highlightColor = "#073355"

[Params.logo]
    image = "img/logos/fms-choir-logo-200.webp"
    title = "FMS Choir"
    subtitle = "Forestwood Middle School"

[Params.sidebar]
  home = "right"
  list = false
  single = false
  widgets = ["recent","choirschedule","about","social","fms"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  facebook = "groups/834672333219924" #"Forestwood Middle School Choir Booster Club"
  # twitter = "FMHSWaterJags"
  # twitter2 = "waterpolofmhs"
  instagram = "fmschoir"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  email = "lavacekk@lisd.net"

[Params.links]
  voly = "https://lewisvilleisd.voly.org/"
  privlesson24 = "https://forms.gle/AsM1RubUen3t5T1bA" #"https://docs.google.com/forms/d/e/1FAIpQLScT65BA5qDjGyeayTUDK1bDvhmgUqobd3NSK4PybrDSNAwccQ/viewform" #qrco.de/bfHFkm #https://forms.gle/AsM1RubUen3t5T1bA
  privlesson = "https://docs.google.com/forms/d/e/1FAIpQLSckQLk_sUsoJ38-VTDSv9n7x4wk2VEk3FMa2541qjkCqiBYkw/viewform?usp=header"
  choirvol24 = "https://docs.google.com/forms/d/e/1FAIpQLSdHg1psmgA6P9D8PF_OvYDEwdg5l1aPM7ue3pjP_DxO-IvI4w/viewform"
  choirvol = "https://docs.google.com/forms/d/e/1FAIpQLScXPKlRmcFLRa-wKm5VZFmDx2IwmAO8vMIGbrpcWdOI5VRaGQ/viewform?usp=sharing&ouid=109247476285912656444"
  handbookdoc = "https://docs.google.com/document/d/13lnsDlwdar1fkq3TjyW7uzxTn0bKOTWYrZLuS0MFQJw/edit?tab=t.0#heading=h.nj23sjpj5u97" #qrco.de/bfHliW
  handbooksigform24 = "https://forms.gle/Nq1hvwaxEt3iNMCb9"
  handbooksigform = "https://docs.google.com/forms/d/e/1FAIpQLSd61pLsM31_CW4iT1k55i9hOxpEikmsRxRN-118sbte8p-wsA/viewform?usp=dialog"
  spirit6th = "https://my.cheddarup.com/c/forestwood-ms-choir-6th-grade-supplies-spiritwear-2024-2025/items" 
  spirit78th = "https://my.cheddarup.com/c/forestwood-ms-choir-7th-8th-grade-supplies-spir-49231/items"
  calendar24 = "https://docs.google.com/document/d/1OSm4CIuz83e_xXSEVUsSVnf4rwPYuu5Hhpivxp-LFYQ/edit#heading=h.3f0ls4ew76cz"
  calendar25 = "https://docs.google.com/document/d/1idmaOdWU2YZXnhOTtjgDEHXzKlV5iuBOK1j4NkKq2Xo/edit?tab=t.0#heading=h.3f0ls4ew76cz"
  gcal = "https://calendar.google.com/calendar/embed?height=600&wkst=1&ctz=America%2FChicago&showPrint=0&showTz=0&src=Y18wOGE1MjJkMzEwZmZmNzY4ZjhjMmVkYTc3MTcxY2ZiYTAyYTFhZTc2OWIxYzVkYWE3N2I0ZjI1NjQyZDM5YzU0QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23b39ddb"
  feeform = "https://docs.google.com/document/d/1iQbounwkE5vJPBMg1ViiE15DxUTSgNJWuZAKi15n2Eg/edit?tab=t.0#heading=h.nj23sjpj5u97"
  photos24 = "https://drive.google.com/drive/folders/1esneRj2TeqjIZhcwWGHCDRNOfcX9xrRd"
  photos25 = "https://drive.google.com/drive/folders/1Gmfx8W3DbliGfrHBhfqYs7xDohBFwJEf"

# [Params.widgets.search]
#   cached = false # activate cache if true
#   url = "https://google.com/search"
#   [Params.widgets.search.input]
#     name = "sitesearch"
#     pre = ""

##
# menu
##
[Menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
# [[menu.main]]
#     name = 'Roster'
#     pageRef = '/roster'
#     weight = 10
[[menu.main]]
    name = 'Directors'
    pageRef = '/directors'
    weight = 20
[[menu.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 21
[[menu.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 30
# [[menu.main]]
#     name = 'Events'
#     pageRef = '/events'
#     weight = 31
[[menu.main]]
    name = 'Spirit Nights'
    pageRef = '/spirit-nights'
    weight = 32
# [[menu.main]]
#     name = 'Volunteer'
#     pageRef = '/volunteer'
#     weight = 40
# [[menu.main]]
#     name = 'Photos'
#     pageRef = '/photos'
#     weight = 60
# [[menu.main]]
#     name = 'Booster Info'
#     pageRef = '/booster-info'
#     weight = 61
# [[menu.main]]
#     name = 'Spirit Wear'
#     url = 'https://kristees.biz/collections/swim-and-dive'
#     weight = 70
#     [menu.main.params]
#         external = true
# [[menu.main]]
#     name = 'Forms'
#     pageRef = '/forms'
#     weight = 80
[[menu.main]]
    name = 'Choir Handbook'
    pageRef = '/handbook'
    weight = 81
[[menu.main]]
    name = 'Cantus'
    pageRef = '/cantus'
    weight = 82
# [[menu.main]]
#     name = "sub-menu"
#     url = '/forms'
#     parent = "Forms"
## 
# menu footer
##
[[menu.footer]]
    name = 'Home'
    pageRef = '/'
    weight = 1
# [[menu.footer]]
#     name = 'Roster'
#     pageRef = '/roster'
#     weight = 10
# [[menu.footer]]
#     name = 'Volunteer'
#     pageRef = '/volunteer'
#     weight = 40
# [[menu.footer]]
#     name = 'Booster Info'
#     pageRef = '/booster-info'
#     weight = 50
# [[menu.footer]]
#     name = 'Spirit Wear'
#     url = 'https://kristees.biz/collections/swim-and-dive'
#     weight = 70
#     [menu.main.params]
#         rel = 'external'
[[menu.footer]]
    name = 'Choir Handbook'
    pageRef = '/handbook'
    weight = 80

